const express = require('express');
const CityController = require('../../controllers/city-controller');
const router = express.Router();
const FlightController = require('../../controllers/flight-controller');
const AirportController = require('../../controllers/airport-controller');
router.post('/flight',FlightController.create);
router.post('/city', CityController.create);
router.get('/city/:id', CityController.get);
router.patch('/city/:id', CityController.update);
router.delete('/city/:id', CityController.destroy);
router.get('/city',CityController.getall);
router.get('/flight',FlightController.getall);
router.post('/airport',AirportController.create);
//router.get('/airport/:id',AirportController);
//router.get('/airport',AirportController.getall);
//router.patch('/airport/:id',AirportController.update);
//router.delete('/airport/:id',AirportController.destroy);
module.exports = router;
